name: Auto Merge DeviceHub PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    if: startsWith(github.head_ref, 'devicehub/update-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.DEVICEHUB_GH_PAT }}

      - name: Auto merge PR
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.DEVICEHUB_GH_PAT }}
          MERGE_METHOD: squash
